language: perl

sudo: false

perl:
    - "5.26"
    
addons:
    apt:
        packages:
            - zip
            - gzip
            - git
            - curl

env:
  - BLASTVER=2.9.0

install:
    - "cpanm --quiet --notest JSON Path::Tiny LWP::Simple Bio::Perl"
    - "wget http://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/${BLASTVER}/ncbi-blast-${BLASTVER}+-x64-linux.tar.gz"
    - "tar zxvf ncbi-blast-${BLASTVER}+-x64-linux.tar.gz"
    - "curl https://raw.githubusercontent.com/tseemann/any2fasta/master/any2fasta > bin/any2fasta"
    - "chmod +x bin/any2fasta"
    - "export PATH=$PWD/bin:$PWD/ncbi-blast-${BLASTVER}+/bin:$PATH"

script:
    - "abricate --setupdb"
    - "abricate --version"
    - "abricate --help"
    - "abricate --check"
    - "abricate --list"
    - "! abricate --doesnotexist"
    - "! abricate --threads 0"
    - "! (abricate test/assembly.fa | grep '~~~')"
    - "abricate test/assembly.fa > 1.tab"
    - "abricate test/assembly.fa.gz > 2.tab"
    - "abricate test/assembly.gbk > 3.tab"
    - "abricate test/assembly.gbk.gz > 4.tab"
    - "abricate --nopath test/assembly.gbk.gz | grep '^assembly.gbk.gz'"
    - "abricate --summary {1,2,3,4}.tab > summary.tab"
    - "abricate --summary 1.tab 2.tab 1.tab |& grep 'duplicate'"
    - "abricate not_exist.embl |& grep ERROR"
    - "abricate --threads `nproc` test/assembly.fa.bz2 | grep -i FOSFOMYCIN"
    - "abricate --threads `nproc` test/assembly.fa.bz2 | grep -i lactam"
    - "for DB in `abricate --list | cut -f1`; do abricate --db $DB test/assembly.fa > /dev/null ; done"
    - "abricate-get_db --help"
    - "abricate-get_db --db card --dbdir ."
